---
title: "NCME Conference"
format: 
  html:
    page-layout: full
---

+------------------+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| # Time           | # Friday                                                                                                              | # Saturday                                                                                                                           | # Sunday                                                                                                      |
|                  |                                                                                                                       |                                                                                                                                      |                                                                                                               |
| 7:45 - 9:15 am   | ### Keynote Lecture                                                                                                   |                                                                                                                                      | [Recent Innovations in Automated Scoring](http://tinyurl.com/yo7taytt)                                        |
|                  |                                                                                                                       |                                                                                                                                      |                                                                                                               |
|                  |                                                                                                                       |                                                                                                                                      | Floor: First, 120C\                                                                                           |
|                  |                                                                                                                       |                                                                                                                                      | \                                                                                                             |
|                  |                                                                                                                       |                                                                                                                                      | [Automated Scoring II](http://tinyurl.com/yt43swe3)                                                           |
|                  |                                                                                                                       |                                                                                                                                      |                                                                                                               |
|                  |                                                                                                                       |                                                                                                                                      | Floor: First, 121C                                                                                            |
+------------------+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| 9:35 - 10:05 am  | ### Keynote Lecture                                                                                                   |                                                                                                                                      | [Innovations and Practices of AI and Language Models in Large-Scale Assessments](http://tinyurl.com/yv8dkquy) |
|                  |                                                                                                                       |                                                                                                                                      |                                                                                                               |
|                  |                                                                                                                       |                                                                                                                                      | Floor: First, 121A                                                                                            |
|                  |                                                                                                                       |                                                                                                                                      |                                                                                                               |
|                  |                                                                                                                       |                                                                                                                                      | [Machine Learning Aspects of Computational Psychometrics](http://tinyurl.com/yq87dlk2)                        |
|                  |                                                                                                                       |                                                                                                                                      |                                                                                                               |
|                  |                                                                                                                       |                                                                                                                                      | Floor: First, 124                                                                                             |
+------------------+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| 10:05 - 11:05 am | [Using Generative AI in Education: Results from Large-Scale EdTech Platform R&D](http://tinyurl.com/2x97fqkj)         |                                                                                                                                      | [Machine Learning Aspects of Computational Psychometrics](http://tinyurl.com/yq87dlk2)                        |
|                  |                                                                                                                       |                                                                                                                                      |                                                                                                               |
|                  | Floor: Fourth, Terrace Ballroom III                                                                                   |                                                                                                                                      | Floor: First, 124                                                                                             |
+------------------+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| 11:25 - 12:25 pm | [Applications of AI](http://tinyurl.com/yv6hjdyq)                                                                     | [GSIC Poster Session II](http://tinyurl.com/yudn8tpy)                                                                                |                                                                                                               |
|                  |                                                                                                                       |                                                                                                                                      |                                                                                                               |
|                  | Floor: First, 124                                                                                                     | Floor: Fourth, Terrace Ballroom IV                                                                                                   |                                                                                                               |
+------------------+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| 1:15 - 2:45pm    | [Assessment on the AI: Challenges and Opportunities of Leveraging Large Language Model](http://tinyurl.com/yrekfjp9)\ | [Tackling Challenges in Automated Scoring: Data Augmentation, Multilingualism, and Feedback Mechanisms](http://tinyurl.com/yvhynk5x) | [Electronic Board Session II](http://tinyurl.com/ylm9xnzk)                                                    |
|                  | \                                                                                                                     |                                                                                                                                      |                                                                                                               |
|                  | Floor: First, 121C                                                                                                    | Floor: First, 121C                                                                                                                   | Floor: Fourth, Terrace Ballroom IV                                                                            |
|                  |                                                                                                                       |                                                                                                                                      |                                                                                                               |
|                  | [Automated Scoring I](http://tinyurl.com/ymk5yghw)                                                                    | [Innovation Demonstration II](http://tinyurl.com/ypqy59tz)                                                                           |                                                                                                               |
|                  |                                                                                                                       |                                                                                                                                      |                                                                                                               |
|                  | Floor: First, 125                                                                                                     | Floor: Fourth, Terrace Ballroom IV                                                                                                   |                                                                                                               |
|                  |                                                                                                                       |                                                                                                                                      |                                                                                                               |
|                  | [Innovation Demonstration I](http://tinyurl.com/ywsx6km5)                                                             | [Scaling, Linking, and Equating in Automatic Item Generation](http://tinyurl.com/yp93m84q)                                           |                                                                                                               |
|                  |                                                                                                                       |                                                                                                                                      |                                                                                                               |
|                  | Floor: Fourth, Terrace Ballroom IV                                                                                    | Floor: First, 123                                                                                                                    |                                                                                                               |
|                  |                                                                                                                       |                                                                                                                                      |                                                                                                               |
|                  | [Revolutionizing Alignment and Tagging Using AI: Results from the Front Lines](http://tinyurl.com/ylhv264g)           |                                                                                                                                      |                                                                                                               |
|                  |                                                                                                                       |                                                                                                                                      |                                                                                                               |
|                  | Floor: First, 123                                                                                                     |                                                                                                                                      |                                                                                                               |
|                  |                                                                                                                       |                                                                                                                                      |                                                                                                               |
|                  | [Innovations in the Measurement of 21st Century Skills](http://tinyurl.com/yuh4lmw3)                                  |                                                                                                                                      |                                                                                                               |
|                  |                                                                                                                       |                                                                                                                                      |                                                                                                               |
|                  | Floor: First, 120C                                                                                                    |                                                                                                                                      |                                                                                                               |
+------------------+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| 3:05 - 4:35 pm   |                                                                                                                       | [One Year After GPT-4: How AI Changed Assessments?](http://tinyurl.com/ys7rdmq6)                                                     | [Addressing Fairness Concerns in Digital-First, AI-Powered Testing Environments](http://tinyurl.com/ykw669h7) |
|                  |                                                                                                                       |                                                                                                                                      |                                                                                                               |
|                  |                                                                                                                       | Floor: Fourth, Terrace Ballroom III\                                                                                                 | Floor: First, 121C                                                                                            |
|                  |                                                                                                                       | \                                                                                                                                    |                                                                                                               |
|                  |                                                                                                                       | [Automatic Item Generation](http://tinyurl.com/ywj65856)                                                                             |                                                                                                               |
|                  |                                                                                                                       |                                                                                                                                      |                                                                                                               |
|                  |                                                                                                                       | Floor: First, 121C                                                                                                                   |                                                                                                               |
+------------------+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| 4:55 - 6:25 pm   |                                                                                                                       | [Sparking a Debate on the Role of Artificial Intelligence in Educational Measurement](http://tinyurl.com/ymwe9gdn)\                  |                                                                                                               |
|                  |                                                                                                                       | \                                                                                                                                    |                                                                                                               |
|                  |                                                                                                                       | Floor: Fourth, Terrace Ballroom III                                                                                                  |                                                                                                               |
+------------------+-----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
