project:
  type: website
  output-dir: docs
    
website:
  title: "Generative AI in Measurement for Education"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - open-datasets-code.qmd
      - events.qmd
      - literature.qmd

bibliography: references.bib

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

