project:
  type: website
  output-dir: docs

website:
  title: "gaime"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - datasets.qmd
      - events.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

