project:
  type: website
  output-dir: docs
    
website:
  navbar:
    logo: images/logo-no-background.png
    left:
      - index.qmd
      - about.qmd
      - open-datasets.qmd
      - events.qmd
      - literature.qmd
    
bibliography: resources/gaime-biblio.bib

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

