---
title: "NCME Conference 2025"
format: 
  html:
    page-layout: full
---

+------------+---------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| # Time     | # Thursday                                                                                              | # Friday                                                                                                      | # Saturday                                                                                             |
|            |                                                                                                         |                                                                                                               |                                                                                                        |
|            | ###                                                                                                     |                                                                                                               |                                                                                                        |
+------------+---------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 8:00-9:30  | Generative AI in Education: Applied Ethics                                                              | Presidential Address                                                                                          | Recent Theoretical AI Developments in Educational Assessment                                           |
|            |                                                                                                         |                                                                                                               |                                                                                                        |
|            | Denver 1-2                                                                                              |                                                                                                               | Denver 5-6                                                                                             |
|            |                                                                                                         |                                                                                                               |                                                                                                        |
|            |                                                                                                         |                                                                                                               | Using Large Language Models within Item Development Workflows                                          |
|            |                                                                                                         |                                                                                                               |                                                                                                        |
|            |                                                                                                         |                                                                                                               | Colorado IJ                                                                                            |
+------------+---------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 9:45-11:15 | Innovations in Using Large Language Models for Automated Scoring and Automated Writing Evaluation       | AI Innovative Applications in Automated Scoring                                                               | Leveraging Large-Language Models for Operational Large-Scale Assessments: Opportunities and Challenges |
|            |                                                                                                         |                                                                                                               |                                                                                                        |
|            | Denver 5-6                                                                                              | Colorado AB                                                                                                   | Denver 12                                                                                              |
|            |                                                                                                         |                                                                                                               |                                                                                                        |
|            |                                                                                                         | Comparing Approaches to Reduce Vulnerabilities and Improve Performance of Large Language Models in Assessment | Psychometrically-driven Product Development in the Age of AI                                           |
|            |                                                                                                         |                                                                                                               |                                                                                                        |
|            |                                                                                                         | Denver 3                                                                                                      | Colorado EF                                                                                            |
+------------+---------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 11:30-1:00 | Test Security in the AI Age: Trends, Challenges, and Visions                                            | Innovations in Automated Scoring Modeling                                                                     | Expanding Automated Scoring Validity & Generalizability using AI                                       |
|            |                                                                                                         |                                                                                                               |                                                                                                        |
|            | Penrose 1                                                                                               | Colorado AB                                                                                                   | Denver 12                                                                                              |
|            |                                                                                                         |                                                                                                               |                                                                                                        |
|            |                                                                                                         |                                                                                                               | Understanding AI and Human Ratings: Complementary Roles of AI and Human Raters                         |
|            |                                                                                                         |                                                                                                               |                                                                                                        |
|            |                                                                                                         |                                                                                                               | Denver 3                                                                                               |
+------------+---------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 1:30-3:00  | Comparing Approaches for Using Large Language Models for Scoring and Specialized Assessments            | LLM respondents in Measurement                                                                                | Applications of Large Language Models to Automated Scoring and Feedback                                |
|            |                                                                                                         |                                                                                                               |                                                                                                        |
|            | Denver 5-6                                                                                              | Colorado AB                                                                                                   | Colorado IJ                                                                                            |
+------------+---------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 3:15:4:15  | Applications of Generative AI to Mathematics Education: Opportunities and Challenges                    |                                                                                                               |                                                                                                        |
|            |                                                                                                         |                                                                                                               |                                                                                                        |
|            | Penrose 2                                                                                               |                                                                                                               |                                                                                                        |
|            |                                                                                                         |                                                                                                               |                                                                                                        |
|            | Using AI to Address Challenges in Scoring and Automated Feedback                                        |                                                                                                               |                                                                                                        |
|            |                                                                                                         |                                                                                                               |                                                                                                        |
|            | Denver 4                                                                                                |                                                                                                               |                                                                                                        |
+------------+---------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
| 4:30-6:00  | Generative-AI automatic item generation for large-scale language assessments                            | From Principles to Practice: Operationalizing Responsible AI in Educational Measurement                       |                                                                                                        |
|            |                                                                                                         |                                                                                                               |                                                                                                        |
|            | Colorado AB                                                                                             | Colorado EF                                                                                                   |                                                                                                        |
|            |                                                                                                         |                                                                                                               |                                                                                                        |
|            | Using AI and Machine Learning to Improve Data on Students' Educational Progress in the US and Worldwide | Using Large Language Models for Alignment and Progression Tasks                                               |                                                                                                        |
|            |                                                                                                         |                                                                                                               |                                                                                                        |
|            | Denver 3                                                                                                | Colorado CD                                                                                                   |                                                                                                        |
+------------+---------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+
