---
title: "Artificial Intelligence in Measurement and Education"
 
format: 
  revealjs:
    logo: ../../images/logo-no-background-name.png
    theme: [default, aime_theme.scss]
---

## Introductions

### Executive Board

-   Co-Chair: Chris Ormerod

-   Co-chair: John Whitmer

-   Secretary: Maggie Beiting-Parrish

## Outline

-   AIME Updates

-   Research Presentation: Alex Scarlatos, University of Massachusetts Amherst, "Exploring Knowledge Tracing in Tutor-Student Dialogues using LLMs"

-   Additional SIG Updates & Calls for Participation

## AIME Updates


## Recent Special Issues

Two recent special issues have appeared featuring the work of members:

### Chinese English Journal of Educational Measurement and Evaluation

#### Artificial Intelligence and Machine Learning in Educational Measurement

[https://www.ce-jeme.org/journal/vol5/iss3/](https://www.ce-jeme.org/journal/vol5/iss3/)

### Journal of Measurement and Evaluation in Education and Psychology

#### Opportunities and Challenges of AI in Educational Assessment

[https://dergipark.org.tr/en/pub/epod/issue/84493 ](https://dergipark.org.tr/en/pub/epod/issue/84493 )


### AIME conference (Proposal).

We are submitting proposal for a Special AI in Measurement and Education Conference

Submitted by: AIME SIG Conference Organizing Committee (Joshua Wilson as Committee Chair)

**Theme:** Building Robust Evidence for AI in Educational Measurement

**Possible topics**

-   AI Applications in Measurement and Assessment

-   AI applications in Instruction

-   Ethical Issues

-   Assessment Opportunities and Challenges

-   Building Technological Expertise

The conference is being put toward the board for approval on 1/15. The most likely location is Pittsburgh.

## AIME Updates

### NCME Annual Meeting

The theme of the 2025 NCME Annual Meeting is "Educational Measurement: In Service of Society." The theme emphasizes the "why" of our work in educational measurement and echoes the last three words of the [NCME mission](https://www.ncme.org/about/about-ncme/mission): "to advance theory and applications of educational measurement **to benefit society**"

**Dates:** April 23-26, 2025

**Place:** Denver, CO

### Next Meeting

Speaker suggestions? Self-nominations welcome!

## Research Presentation

Alex Scarlatos, University of Massachusetts, Amherts

Exploring Knowledge Tracing in Tutor-Student Dialogues using LLMs

# Additional SIG Updates & Calls for Participation


## Special Issue of Assessing Writing 

Joshua Wilson and Corey Palermo are co-editing a special issue, titled **“AI and Writing Assessment: Innovations, Validity, and Ethical Considerations.”** This special issue aims to advance the field’s understanding of how AI can be responsibly and effectively integrated into writing assessment, with a focus on innovation, validity, and ethics.

**Abstract Deadline:** 31st of March, 2025

**Submission Deadline:** 1st of October, 2025

**Contacts:**

-   Dr. Joshua Wilson (University of Delaware): [joshwils\@udel.edu](mailto:joshwils@udel.edu "mailto:joshwils@udel.edu")

-   Dr. Corey Palermo (Measurement Incorporated): [cpalermo\@measinc.com](mailto:cpalermo@measinc.com "mailto:cpalermo@measinc.com")

## Building Educational Applications (BEA)

The **BEA Workshop** is a leading venue for NLP innovation in the context of educational applications. It is one of the largest one-day workshops in the ACL community with over 100 registered attendees in the past several years.

<https://sig-edu.org/bea/2025>

**Place:** Vienna, Austria

**Date:** July 31 and August 1, 2025

## 26th International Conference on Artificial Intelligence in Education

AIED 2025 will be the 26th edition and celebrates the quarter of century advancing science and engineering of intelligent human-technology ecosystems that support learning. The conference will be the latest of a longstanding series of international conferences, known for high quality and innovative research on AI-assisted systems and cognitive science approaches for educational computing applications.

**Dates:** July 22-26, 2025

**Place:** Palermo, Italy

<https://iaied.org/conferences>

# Thank You
